services:
  fastzero_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lucas
      POSTGRES_DB: armiger_db
      POSTGRES_PASSWORD: o38SQ5Y15u9G
    ports:
      - "5432:5432"

  fastzero_app:
    image: fastzero_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - fastzero_database
    environment:
      DATABASE_URL: postgresql+psycopg://lucas:o38SQ5Y15u9G@fastzero_database:5432/armiger_db

volumes:
  pgdata: